# removed for now as they are broken: LeftContinuation, ProgramMultipleSuspendLeft, ZeroArgumentsMultipleResume, ZeroArgumentsTwoContinuationsMultipleResume
sbt "examples/runMain examples.main; \
examples/runMain examples.ZeroArgumentsTwoContinuations; \
examples/runMain examples.ZeroArgumentsTwoContinuationsCF; \
examples/runMain examples.TwoContinuationsUseCodeAboveContinuationInCodeAfterTheContinuation; \
examples/runMain examples.TwoArgumentsSingleResumeContinuationsCodeAfter; \
examples/runMain examples.GenericArgumentsSingleResumeContinuations; \
examples/runMain examples.TwoArgumentsSingleResumeContinuations; \
examples/runMain examples.ZeroArgumentsSingleResumeContinuationsCodeAfter; \
examples/runMain examples.TwoCurriedArgumentsTwoContinuations; \
examples/runMain examples.ZeroArgumentsOneContinuationsCF; \
examples/runMain examples.TwoArgumentsOneContinuationsCF; \
examples/runMain examples.TwoArgumentsZeroContinuationsCF; \
examples/runMain examples.TwoArgumentsSingleResumeContinuationsBeforeUsedInResume; \
examples/runMain examples.TwoArgumentsTwoContinuations; \
examples/runMain examples.OneArgumentOneAdditionalGivenArgumentTwoContinuations; \
examples/runMain examples.ZeroArgumentsZeroContinuations; \
examples/runMain examples.TwoContinuationsUseCodeAboveContinuationsInCodeBetweenContinuations; \
examples/runMain examples.OneFunctionParameterOneResume; \
examples/runMain examples.TwoArgumentsSingleResumeContinuationsBefore; \
examples/runMain examples.OneArgumentSingleResumeContinuationsCodeAfter; \
examples/runMain examples.ZeroArgumentsSingleResumeContinuations; \
examples/runMain examples.MultipleSuspendWithExpressionsInBody; \
examples/runMain examples.PolymorphicDefsZeroContinuations; \
examples/runMain examples.ZeroArgumentsZeroContinuationsCF; \
examples/runMain examples.OneArgumentsOneContinuationsCF; \
examples/runMain examples.OneArgumentsTwoContinuations; \
examples/runMain examples.OneArgumentsSingleResumeContinuationsBefore; \
examples/runMain examples.OneArgumentOneCurriedArgumentZeroContinuations; \
examples/runMain examples.ZeroArgumentsValsDefinedInsideResume; \
examples/runMain examples.ListMap; \
examples/runMain examples.GenericArgumentsContinuations; \
examples/runMain examples.ZeroArgumentsSingleResumeContinuationsBefore; \
examples/runMain examples.TwoCurriedArgumentsOneContinuations; \
examples/runMain examples.TwoArgumentsTwoDependentContinuations; \
examples/runMain examples.UseValsDefinedInsideContinuation; \
examples/runMain examples.OneFunctionParamZeroContinuations; \
examples/runMain examples.OneArgumentOneAdditionalGivenArgumentZeroContinuations; \
examples/runMain examples.OneArgumentsTwoContinuationsCF; \
examples/runMain examples.GenericArgumentsZeroContinuations; \
examples/runMain examples.ZeroArgumentsCodeAfter; \
examples/runMain examples.OneArgumentsZeroContinuationsCF; \
examples/runMain examples.ZeroArgumentsValsDefinedAboveContinuation; \
examples/runMain examples.TwoArgumentsTwoContinuationsCF; \
examples/runMain examples.ZeroArgumentsCodeBetween; \
examples/runMain examples.ResumeWithValsInsideTheContinuation; \
examples/runMain examples.ZeroArgumentsValsDefinedInsideContinuation; \
examples/runMain examples.ZeroArgumentsOneContinuationCodeBeforeUsedAfter; \
examples/runMain examples.OneArgumentOneAdditionalGivenArgumentOneContinuations; \
examples/runMain examples.ThreeDependentContinuations; \
examples/runMain examples.OneArgumentsZeroContinuations; \
examples/runMain examples.ZeroArgumentsCodeBefore; \
examples/runMain examples.OneArgumentsSingleResumeContinuations; \
examples/runMain examples.OneFunctionArgumentTwoContinuationsTwoResumes; \
examples/runMain examples.TwoArgumentsZeroContinuations; \
examples/runMain examples.AbstractClassContinuations; \
examples/runMain examples.NonCompanionObjectContinuations"
